### ISSUE TITLE
Update to Phoenix 1.3 directory

### ISSUE THREAD

**Issue by yuchunc** [christopheradams/phoenix_rest#1]
I am attempting to add a mix task for generating resource in Phoenix 1.3's new directory architecture.

https://github.com/yuchunc/phoenix_rest/tree/new_phoenix_dir

However, at [generator L28](https://github.com/yuchunc/phoenix_rest/blob/new_phoenix_dir/lib/mix/tasks/phx_rest.gen.resource.ex#L28) with [plug_rest's generator L57](https://github.com/christopheradams/plug_rest/blob/master/lib/mix/tasks/plug_rest.gen.resource.ex#L57), will produce some unexpected behaviour:

```
> mix phx_rest.gen.resource FooResource
# Heqet.Web.FooResource created at ./lib/heqet/web/resources/web/foo_resource.ex
```

One idea on fixing this is update plug_rest's generator and parse on option `:dir`, if end with `.ex`, don't underscore. Then phoenix_rest can construct the complete `:dir` and pass it on.

What do you think?

**Comment by christopheradams** [comment]
Yes, I see it's a problem. PlugRest is not expecting a namespaced resource module like `Web.FooResource` and is creating an extra `/web` directory from the name. 

What about fixing this in PlugRest call to`Macro.underscore/1`, either making it use the last part of the module name (cut off `Web.` to get `FooResource`) or the last part of the path (cut off `web/` to get`foo_resource`)?

Or an alternative solution more like you're suggesting is to add maybe a `:path` option to PlugRest that takes a complete filename and doesn't try to guess it from the module name.

Or perhaps the new phx generators would have some clues about how to approach this.

What do you think?

**Comment by yuchunc** [comment]
I think slicing the module name may make the behaviour of this generator "surprising" from time. I am in favour of: "When user gives a complete path, use that and don't guess from module name." That would be adding the `path` option to plug_rest.

Also, this function is probably helpful.
https://github.com/phoenixframework/phoenix/blob/751516ac4f501870352ddee5fc1c409b5c808c0d/lib/mix/phoenix.ex#L115

It can be added to phoenix_rest, it will checks if the module name is redundant.

**Comment by christopheradams** [comment]
Release v0.5.0 with this change. Thanks!
