### ISSUE TITLE
Update to support Phoenix 1.4

### ISSUE THREAD

**Issue by hjalet** [christopheradams/phoenix_rest#3]
We would like to use phoenix_rest for our REST APIs.
Is this project still maintained? Is it possible to get it upgraded to newest Phoenix 1.4?
The Phoenix dependency conflicts and the Mix task for generating a resource with the callbacks implemented fails with the following error:
```
** (MatchError) no match of right hand side value: true
    lib/mix/tasks/plug_rest.gen.resource.ex:90: Mix.Tasks.PlugRest.Gen.Resource.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

Also the version of Cowboy conflicts, but thats probably in the `plug_rest` project?

**Comment by christopheradams** [comment]
The underlying issue here is detailed in christopheradams/plug_rest#7. It has nothing to due with Phoenix versions, but I can look into updating the dependencies.

**Comment by christopheradams** [comment]
PhoenixRest v0.7.0 has added Phoenix 1.4 support.
